### ISSUE TITLE
Got information at the top of the OGC

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/omar#53]
data2/tilestore_test/brevard_county/q3306nw.tif -  image space – export – OGC WMS Capability – Got information at the top of the OGC - This XML file does not appear to have any style information associated with it. The document tree is shown below. I don’t why but don’t remember seeing this before.

**Comment by sbortman** [comment]
This is not a bug.  The WMS GetCapabilities is an XML document meant for process interoperability rather than user consumption.  Really the user just copy/pastes the URL into something like QGIS or ArcView,  etc to pull data.   I suppose we could "pretty up" the XML view with a stylesheet.
