### ISSUE TITLE
10 Most Recent Image not work from Home Page

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/omar#63]
Home Page – KML Network Link - 10 Most Recent Images For View – downloaded the KML but was not able to load in GE – Could see the download but could not load in GE.

**Comment by sbortman** [comment]
This feature depends on images that have an acquision_date that is not null.   The omar.ossim.org database was purged to all but a few for testing of AGC tile store app.   And,  there are no images in the current database that meet the minimum criteria.   Tested locally and it behaves as expected.
